name: C Tests Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc make

      - name: Build Project
        run: make

  memory-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc make

      - name: Compile and Run Memory Tests
        run: |
          gcc -o test_memory tests/test_memory.c src/memory.c src/unity/unity.c
          ./test_memory

  cache-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc make

      - name: Compile and Run Cache Tests
        run: |
          gcc -o test_cache tests/test_cache.c src/cache.c src/unity/unity.c -Iinclude -lm
          ./test_cache
