name: C Tests Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up build environment
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc make

      # Step 3: Compile tests
      - name: Compile Tests
        run: gcc -o test_memory tests/memory/test_memory.c src/memory.c src/unity/unity.c

      # Step 4: Run tests
      - name: Run Tests
        run: ./test_memory
